version: '3.9'

services:
  backend:
    build:
      context: ./backend-app
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend-app/Red Theatre
    ports:
      - "3000:3000"
    depends_on:
      - backend